version: '3.5'

services:
  app:
    build: .
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
      - '49153:49153'
    command: ng serve --host 0.0.0.0 --poll=1000